"""
Django settings for job_recruitment project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from dj_database_url import parse as db_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [

    'dal',  # new
    'dal_select2',  # new

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # new

    'import_export',  # new
    'django_ses',  # new

    'rest_framework',  # new
    'corsheaders',  # new

    'c_auth',  # new
    'app',  # new
    'primary_data',  # new
    'employer',  # new
    'jobseeker',  # new
    'job',  # new
    'api',  # new
]

# custom user model
AUTH_USER_MODEL = 'c_auth.User'  # new

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'job_recruitment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'job_recruitment.wsgi.application'


# django default
LOGIN_REDIRECT_URL = 'faq'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# sqlite3
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# postgresql
# DATABASES = {
#     'default': {
#         'ENGINE': config('RDS_ENGINE', default='django.db.backends.postgresql'),
#         'HOST': config('RDS_HOST', default=''),
#         'NAME': config('RDS_NAME', default=''),
#         'USER': config('RDS_USER', default=''),
#         'PASSWORD': config('RDS_PASSWORD', default=''),
#         'PORT': config('RDS_PORT', default=''),
#         'TIME_ZONE': config('RDS_TIME_ZONE', default='Asia/Kolkata'),
#     }
# }

# postgresql / mysql
DATABASES = {"default": config("DATABASE_URL", cast=db_url)}
DATABASES["default"]["ATOMIC_REQUESTS"] = True
DATABASES["default"]["CONN_MAX_AGE"] = 60
DATABASES["default"]["TIME_ZONE"] = 'Asia/Kolkata'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = [
    BASE_DIR / 'custom_static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django site
SITE_ID = 1

# default with django for emil
EMAIL_BACKEND = config('EMAIL_BACKEND', default='')
EMAIL_USE_TLS = True
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')  # my g_mail password
EMAIL_PORT = 587
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')  # my g_mail username
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# django ses
EMAIL_BACKEND = config('EMAIL_BACKEND', 'django_ses.SESBackend')
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', '')
AWS_SES_REGION_NAME = config('AWS_SES_REGION_NAME', '')
AWS_SES_REGION_ENDPOINT = config('AWS_SES_REGION_ENDPOINT', '')


# django-cors-headers
CORS_ALLOW_CREDENTIALS = False
CORS_ORIGIN_ALLOW_ALL = False


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
IMPORT_EXPORT_IMPORT_PERMISSION_CODE = 'add'
