# Generated by Django 3.2 on 2021-06-05 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
        ('primary_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_verified', models.BooleanField(default=False)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('resume_headline', models.TextField(blank=True, null=True)),
                ('profile_summary', models.TextField(blank=True, null=True)),
                ('aadhar_number', models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('aadhar_verified', models.BooleanField(default=False)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('pan_verified', models.BooleanField(default=False)),
                ('annual_salary_in_lac', models.PositiveIntegerField(blank=True, choices=[(1, '1 Lac'), (2, '2 Lac'), (3, '3 Lac'), (4, '4 Lac'), (5, '5 Lac'), (6, '6 Lac'), (7, '7 Lac'), (8, '8 Lac'), (9, '9 Lac'), (10, '10 Lac'), (11, '11 Lac'), (12, '12 Lac'), (13, '13 Lac'), (14, '14 Lac'), (15, '15 Lac'), (16, '16 Lac'), (17, '17 Lac'), (18, '18 Lac'), (19, '19 Lac'), (20, '20 Lac'), (21, '21 Lac'), (22, '22 Lac'), (23, '23 Lac'), (24, '24 Lac'), (25, '25 Lac'), (26, '26 Lac'), (27, '27 Lac'), (28, '28 Lac'), (29, '29 Lac'), (30, '30 Lac'), (31, '31 Lac'), (32, '32 Lac'), (33, '33 Lac'), (34, '34 Lac'), (35, '35 Lac'), (36, '36 Lac'), (37, '37 Lac'), (38, '38 Lac'), (39, '39 Lac'), (40, '40 Lac'), (41, '41 Lac'), (42, '42 Lac'), (43, '43 Lac'), (44, '44 Lac'), (45, '45 Lac'), (46, '46 Lac'), (47, '47 Lac'), (48, '48 Lac'), (49, '49 Lac'), (50, '50 Lac'), (51, '51 Lac'), (52, '52 Lac'), (53, '53 Lac'), (54, '54 Lac'), (55, '55 Lac'), (56, '56 Lac'), (57, '57 Lac'), (58, '58 Lac'), (59, '59 Lac'), (60, '60 Lac'), (61, '61 Lac'), (62, '62 Lac'), (63, '63 Lac'), (64, '64 Lac'), (65, '65 Lac'), (66, '66 Lac'), (67, '67 Lac'), (68, '68 Lac'), (69, '69 Lac'), (70, '70 Lac'), (71, '71 Lac'), (72, '72 Lac'), (73, '73 Lac'), (74, '74 Lac'), (75, '75 Lac'), (76, '76 Lac'), (77, '77 Lac'), (78, '78 Lac'), (79, '79 Lac'), (80, '80 Lac'), (81, '81 Lac'), (82, '82 Lac'), (83, '83 Lac'), (84, '84 Lac'), (85, '85 Lac'), (86, '86 Lac'), (87, '87 Lac'), (88, '88 Lac'), (89, '89 Lac'), (90, '90 Lac'), (91, '91 Lac'), (92, '92 Lac'), (93, '93 Lac'), (94, '94 Lac'), (95, '95 Lac'), (96, '96 Lac'), (97, '97 Lac'), (98, '98 Lac')], null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('annual_salary_in_thousand', models.PositiveIntegerField(blank=True, choices=[(0, '0 Thousand'), (5, '5 Thousand'), (10, '10 Thousand'), (15, '15 Thousand'), (20, '20 Thousand'), (25, '25 Thousand'), (30, '30 Thousand'), (35, '35 Thousand'), (40, '40 Thousand'), (45, '45 Thousand'), (50, '50 Thousand'), (55, '55 Thousand'), (60, '60 Thousand'), (65, '65 Thousand'), (70, '70 Thousand'), (75, '75 Thousand'), (80, '80 Thousand'), (85, '85 Thousand'), (90, '90 Thousand'), (95, '95 Thousand')], null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('annual_salary', models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('linked_in_profile', models.URLField(blank=True, null=True)),
                ('twitter_profile', models.URLField(blank=True, null=True)),
                ('youtube_profile', models.URLField(blank=True, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('instagram_profile', models.URLField(blank=True, null=True)),
                ('webpage_link', models.URLField(blank=True, null=True)),
                ('other_link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('complete_profile_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='primary_data.address')),
                ('follow', models.ManyToManyField(blank=True, to='employer.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('web_link', models.URLField(blank=True, null=True)),
                ('start_year', models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('end_year', models.IntegerField(blank=True, choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True)),
                ('status', models.CharField(blank=True, choices=[('I', 'In Progress'), ('F', 'Finished')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_status', models.CharField(blank=True, choices=[('I', 'In Progress'), ('F', 'Finished')], max_length=1, null=True)),
                ('project_start_year', models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('project_end_year', models.IntegerField(blank=True, choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PaperResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('web_link', models.URLField(blank=True, null=True)),
                ('published_year', models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='KnownLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_speak', models.BooleanField(default=False)),
                ('proficiency', models.CharField(blank=True, choices=[('B', 'Beginner'), ('P', 'Proficient'), ('E', 'Expert')], max_length=1, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_data.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('F', 'Full Time'), ('P', 'Part Time')], max_length=1, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_data.designation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
                ('skill', models.ManyToManyField(to='primary_data.KeySkill')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=200)),
                ('certified_by', models.CharField(max_length=200)),
                ('certified_year', models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_Job_type', models.CharField(blank=True, choices=[('P', 'Permanent'), ('C', 'Contractual')], max_length=1, null=True)),
                ('desired_employment_type', models.CharField(blank=True, choices=[('F', 'Full Time'), ('P', 'Part Time')], max_length=1, null=True)),
                ('preferred_shift', models.CharField(blank=True, choices=[('D', 'Day'), ('N', 'Night'), ('F', 'Flexible')], max_length=1, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('functional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_data.functionalarea')),
                ('preferred_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_data.preferredlocation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_data.role')),
            ],
        ),
    ]
